### ISSUE TITLE
a106: Focus Broken

### ISSUE THREAD

**Issue by manjotsidhu** [GODz-Android-Dev/wakemod#5]
Focus is not working maybe due to lens or maybe any other issue ...
Lets solve it ...

**Comment by manjotsidhu** [comment]
Recent Log says :- 
```
E/Sensors (  370): handleToDriver handle(0)
E/Sensors (  370): new setDelay handle(0),ns(200000000)m, error(-1), index(2)
E/Sensors (  370): new setDelay handle(0),ns(200000000) err! go to hwmsen
D/Hwmsen_sensors(  370): setDelay: (handle=0, ns=200000000)
D/Hwmsen_sensors(  370): setDelay: (what=0, ms=200)
D/Hwmsen_sensors(  370): really setDelay: (what=0, ms=200)
E/SensorManager(32282): sensor or listener is null
```

**Comment by manjotsidhu** [comment]
also :-
```
E/LensDrv (  169): Err:   147:, error opening /dev/OV5648AF_DARLING_ZL: No such file or directory
E/af_mgr  (  169): [init()] Err:   307:, m_pMcuDrv->init() fail
```
What I did was just https://github.com/GODz-Android-Dev/android_device_micromax_a106/commit/ad03fd5d165237e623ad8779f8c8a5392ad1c46a 
the error caused to DARLING_ZL driver but not DARLING and other drivers which means there is something wrong **ONLY** with DARLING_ZL

**Comment by imranpopz** [comment]
Compare ramdisk lines from stock kk and lp kernel boot....

**Comment by manjotsidhu** [comment]
@imranpopz  i got these lines from my official stock kitkat kernel source ...

**Comment by manjotsidhu** [comment]
ignore the above commit

**Comment by manjotsidhu** [comment]
https://github.com/GODz-Android-Dev/android_device_micromax_a106/commit/bc795d80a9740ea400dd6d5988f5e0beb88cff61

**Comment by manjotsidhu** [comment]
Fixed !!! Thanks Everyone :+1:
